# Generated by Django 3.2.9 on 2021-11-24 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products_SH6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COD_SH6', models.CharField(max_length=100, unique=True, verbose_name='COD_SH6')),
                ('COD_SH2', models.CharField(blank=True, max_length=100, null=True, verbose_name='COD_SH2')),
                ('NM_SH2', models.CharField(blank=True, max_length=300, null=True, verbose_name='COD_SH6')),
            ],
            options={
                'verbose_name': 'Produto_SH6',
                'verbose_name_plural': 'Produtos_SH6',
            },
        ),
        migrations.CreateModel(
            name='Total_Comex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_Arquivo', models.CharField(max_length=100, unique=True, verbose_name='Nome do Arquivo')),
                ('Movement', models.CharField(max_length=30, verbose_name='Tipo de movimentação')),
                ('Ano', models.CharField(max_length=4, verbose_name='Ano')),
                ('Total', models.BigIntegerField(verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Total_Comex',
                'verbose_name_plural': 'Total_Comex',
            },
        ),
        migrations.CreateModel(
            name='Valor_Movimentado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MOVEMENT', models.CharField(max_length=30, verbose_name='Tipo de movimentação')),
                ('COD_NCM', models.CharField(blank=True, max_length=10, null=True, verbose_name='NM_NCM')),
                ('COD_VIA', models.CharField(blank=True, max_length=10, null=True, verbose_name='NM_NCM')),
                ('ANO', models.CharField(max_length=4, verbose_name='Ano')),
                ('VL_FOB', models.CharField(blank=True, max_length=100, null=True, verbose_name='NM_NCM')),
                ('MONTH', models.CharField(blank=True, max_length=2, null=True, verbose_name='NM_NCM')),
                ('SG_UF', models.CharField(blank=True, max_length=2, null=True, verbose_name='NM_NCM')),
            ],
            options={
                'verbose_name': 'Movimento',
                'verbose_name_plural': 'Movimentações',
            },
        ),
        migrations.CreateModel(
            name='Via',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COD_VIA', models.CharField(max_length=100, unique=True, verbose_name='COD_NCM')),
                ('NM_VIA', models.CharField(blank=True, max_length=300, null=True, verbose_name='NM_NCM')),
            ],
            options={
                'verbose_name': 'Via',
                'verbose_name_plural': 'Vias',
            },
        ),
        migrations.CreateModel(
            name='Products_NCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COD_NCM', models.CharField(max_length=100, unique=True, verbose_name='COD_NCM')),
                ('NM_NCM', models.CharField(blank=True, max_length=300, null=True, verbose_name='NM_NCM')),
                ('COD_SH6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.products_sh6')),
            ],
            options={
                'verbose_name': 'Produto_NCM',
                'verbose_name_plural': 'Produtos_NCM',
            },
        ),
    ]
